// SPDX-FileCopyrightText: 2025 LEDGER SAS
//
// SPDX-License-Identifier: MIT

/*
Use GCC atomic built-in functions from
https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html

Ghidra used the same mnemonic for all atomic instructions and the implementation
of compare-and-exchange was buggy.

This is being fixed with:
https://github.com/NationalSecurityAgency/ghidra/pull/8721 ("Fix disassembly of eBPF atomic
instructions and semantics of compare-and-exchange")
*/
#include <stdbool.h>

#ifndef __clang__
/* clang seems not to support atomic load and store operations */
void atomic_load32(volatile unsigned int *ptr, unsigned int *ret) {
    __atomic_load(ptr, ret, __ATOMIC_RELAXED);
}
unsigned int atomic_load_n32(volatile unsigned int *ptr) {
    return __atomic_load_n(ptr, __ATOMIC_RELAXED);
}
void atomic_load64(volatile unsigned long *ptr, unsigned long *ret) {
    __atomic_load(ptr, ret, __ATOMIC_RELAXED);
}
unsigned long atomic_load_n64(volatile unsigned long *ptr) {
    return __atomic_load_n(ptr, __ATOMIC_RELAXED);
}
void atomic_store32(volatile unsigned int *ptr, unsigned int *val) {
    __atomic_store(ptr, val, __ATOMIC_RELAXED);
}
void atomic_store_n32(volatile unsigned int *ptr, unsigned int val) {
    __atomic_store_n(ptr, val, __ATOMIC_RELAXED);
}
void atomic_store64(volatile unsigned long *ptr, unsigned long *val) {
    __atomic_store(ptr, val, __ATOMIC_RELAXED);
}
void atomic_store_n64(volatile unsigned long *ptr, unsigned long val) {
    __atomic_store_n(ptr, val, __ATOMIC_RELAXED);
}
#endif /* __clang__ */

void atomic_exchange64(volatile unsigned long *ptr, unsigned long *val, unsigned long *ret) {
    __atomic_exchange(ptr, val, ret, __ATOMIC_RELAXED);
}
unsigned long atomic_exchange_n64(volatile unsigned long *ptr, unsigned long val) {
    return __atomic_exchange_n(ptr, val, __ATOMIC_RELAXED);
}

bool atomic_compare_exchange64(volatile unsigned long *ptr, unsigned long *expected, unsigned long *desired) {
    return __atomic_compare_exchange(ptr, expected, desired, 1, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}
bool atomic_compare_exchange_n64(volatile unsigned long *ptr, unsigned long *expected, unsigned long desired) {
    return __atomic_compare_exchange_n(ptr, expected, desired, 1, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}

#if __BPF_CPU_VERSION__ >= 3
/* 32-bit atomic exchange operations */
void atomic_exchange32(volatile unsigned int *ptr, unsigned int *val, unsigned int *ret) {
    __atomic_exchange(ptr, val, ret, __ATOMIC_RELAXED);
}
unsigned int atomic_exchange_n32(volatile unsigned int *ptr, unsigned int val) {
    return __atomic_exchange_n(ptr, val, __ATOMIC_RELAXED);
}

bool atomic_compare_exchange32(volatile unsigned int *ptr, unsigned int *expected, unsigned int *desired) {
    return __atomic_compare_exchange(ptr, expected, desired, 1, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}
bool atomic_compare_exchange_n32(volatile unsigned int *ptr, unsigned int *expected, unsigned int desired) {
    return __atomic_compare_exchange_n(ptr, expected, desired, 1, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}

/*
Use eBPF atomic operations from
https://www.kernel.org/doc/html/v6.0/bpf/instruction-set.html#atomic-operations

Functions generated by:
  for OP in add sub and xor or nand ; do
    cat << EOF
unsigned int atomic_fetch_${OP}32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_${OP}(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_${OP}_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_${OP}_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_${OP}64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_${OP}(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_${OP}_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_${OP}_fetch(addr, value, __ATOMIC_RELAXED);
}
EOF
  done
*/
unsigned int atomic_fetch_add32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_add(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_add_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_add_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_add64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_add(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_add_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_add_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_fetch_sub32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_sub(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_sub_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_sub_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_sub64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_sub(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_sub_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_sub_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_fetch_and32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_and(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_and_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_and_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_and64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_and(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_and_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_and_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_fetch_xor32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_xor(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_xor_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_xor_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_xor64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_xor(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_xor_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_xor_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_fetch_or32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_or(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_or_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_or_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_or64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_or(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_or_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_or_fetch(addr, value, __ATOMIC_RELAXED);
}
#ifndef __clang__
/* clang does not support atomic NAND */
unsigned int atomic_fetch_nand32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_fetch_nand(addr, value, __ATOMIC_RELAXED);
}
unsigned int atomic_nand_fetch32(volatile unsigned int *addr, unsigned int value) {
    return __atomic_nand_fetch(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_fetch_nand64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_fetch_nand(addr, value, __ATOMIC_RELAXED);
}
unsigned long atomic_nand_fetch64(volatile unsigned long *addr, unsigned long value) {
    return __atomic_nand_fetch(addr, value, __ATOMIC_RELAXED);
}
#endif /* __clang__ */

#else /* __BPF_CPU_VERSION__ >= 3 */
/*
Use legacy XADD instruction, which does not return any value

Functions generated by:
  for OP in add sub and xor or nand ; do
    cat << EOF
void atomic_fetch_${OP}64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_${OP}(addr, value, __ATOMIC_RELAXED);
}
void atomic_${OP}_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_${OP}_fetch(addr, value, __ATOMIC_RELAXED);
}
EOF
  done
  for OP in add sub and xor or nand ; do
    cat << EOF
void atomic_fetch_${OP}32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_${OP}(addr, value, __ATOMIC_RELAXED);
}
void atomic_${OP}_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_${OP}_fetch(addr, value, __ATOMIC_RELAXED);
}
EOF
  done
*/
void atomic_fetch_add64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_add(addr, value, __ATOMIC_RELAXED);
}
void atomic_add_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_add_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_sub64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_sub(addr, value, __ATOMIC_RELAXED);
}
void atomic_sub_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_sub_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_and64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_and(addr, value, __ATOMIC_RELAXED);
}
void atomic_and_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_and_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_xor64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_xor(addr, value, __ATOMIC_RELAXED);
}
void atomic_xor_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_xor_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_or64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_or(addr, value, __ATOMIC_RELAXED);
}
void atomic_or_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_or_fetch(addr, value, __ATOMIC_RELAXED);
}
#ifndef __clang__
/* clang does not support atomic NAND */
void atomic_fetch_nand64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_fetch_nand(addr, value, __ATOMIC_RELAXED);
}
void atomic_nand_fetch64_legacy(volatile unsigned long *addr, unsigned long value) {
    __atomic_nand_fetch(addr, value, __ATOMIC_RELAXED);
}
#endif /* __clang__ */
void atomic_fetch_add32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_add(addr, value, __ATOMIC_RELAXED);
}
void atomic_add_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_add_fetch(addr, value, __ATOMIC_RELAXED);
}

#ifndef __clang__
/* clang does not support 32-bit atomics other than add */
void atomic_fetch_sub32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_sub(addr, value, __ATOMIC_RELAXED);
}
void atomic_sub_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_sub_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_and32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_and(addr, value, __ATOMIC_RELAXED);
}
void atomic_and_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_and_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_xor32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_xor(addr, value, __ATOMIC_RELAXED);
}
void atomic_xor_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_xor_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_or32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_or(addr, value, __ATOMIC_RELAXED);
}
void atomic_or_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_or_fetch(addr, value, __ATOMIC_RELAXED);
}
void atomic_fetch_nand32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_fetch_nand(addr, value, __ATOMIC_RELAXED);
}
void atomic_nand_fetch32_legacy(volatile unsigned int *addr, unsigned int value) {
    __atomic_nand_fetch(addr, value, __ATOMIC_RELAXED);
}
#endif /* __clang__ */
#endif /* __BPF_CPU_VERSION__ >= 3 */
